version: "3"
services:
  web:
    build:
      context: .
    image: friendlyhello
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
      - privatenet
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    networks:
      - privatenet
networks:
  webnet:
  privatenet:
